function [result] = check_window(metrics, win_size)
%CHECK_WINDOW Summary of this function goes here
%   Detailed explanation goes here

tolerance_height_abp = 0.05;
tolerance_height_ppg = 0.25;

result = all(metrics.ABP_MIN > 20) && all(metrics.ABP_MAX > 40);

result = result &&...
         all(metrics.ABP_NPK_ST >= floor(win_size*0.75)) &&...
         all(metrics.PPG_NPK_ST >= floor(win_size*0.75)) &&...
         all(metrics.ABP_NPK_ST <= floor(win_size*3)) &&...
         all(metrics.PPG_NPK_ST <= floor(win_size*3));

result = result &&...
         all(metrics.ABP_PPD <= (1/0.75)) &&...
         all(metrics.PPG_PPD <= (1/0.75)) &&...
         all(metrics.ABP_PPD >= (1/3)) &&...
         all(metrics.PPG_PPD >= (1/3));

result = result && all(metrics.PPG_NPK_DT >= metrics.PPG_NPK_ST - 2) &&...
         all(metrics.PPG_NPK_DT <= metrics.PPG_NPK_ST + 2);

result = result &&...
    all(metrics.ABP_PVH >= 1 - tolerance_height_abp) &&...
    all(metrics.PPG_PVH >= 1 - tolerance_height_ppg);

result = result &&...
         all(metrics.ABP_PPH <= tolerance_height_abp) &&...
         all(metrics.PPG_PPH <= tolerance_height_ppg) &&...
         all(metrics.ABP_VVH <= tolerance_height_abp) &&...
         all(metrics.PPG_VVH <= tolerance_height_ppg);
end

