function [result] = check_window(metrics, win_size)
%CHECK_WINDOW Checks if an ABP or PPG signal window is valid

tolerance_height_abp = 0.05;
tolerance_height_ppg = 0.05;

result = all(metrics.ABP_MIN > 20) && all(metrics.ABP_MAX > 40);

result = result &&...
         all(metrics.ABP_NPK_ST >= floor(win_size*0.75)) &&...
         all(metrics.PPG_NPK_ST >= floor(win_size*0.75)) &&...
         all(metrics.ABP_NPK_ST <= floor(win_size*3.33)) &&...
         all(metrics.PPG_NPK_ST <= floor(win_size*3.33));

result = result &&...
        all(metrics.PPG_NPK_DT > ceil(0.25*metrics.PPG_NPK_ST)) &&...
        all(metrics.PPG_NPK_DT <= metrics.PPG_NPK_ST+1);

result = result &&...
         all(metrics.ABP_PPD <= (1/0.75)) &&...
         all(metrics.PPG_PPD <= (1/0.75)) &&...
         all(metrics.ABP_PPD >= (1/3.33)) &&...
         all(metrics.PPG_PPD >= (1/3.33));

result = result &&...
    all(metrics.ABP_PVH >= 1 - tolerance_height_abp) &&...
    all(metrics.PPG_PVH >= 1 - tolerance_height_ppg);

result = result &&...
         all(metrics.ABP_PPH <= tolerance_height_abp) &&...
         all(metrics.PPG_PPH <= tolerance_height_ppg) &&...
         all(metrics.ABP_VVH <= tolerance_height_abp) &&...
         all(metrics.PPG_VVH <= tolerance_height_ppg);
end

